name: Generate daily entry

on:
    schedule:
        - cron: '1 0 * * *'

    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Python configuration
              uses: actions/setup-python@v4
              with:
                  python-version: '3.x'

            - name: Run script
              run: python generate_entry.py

            - name: Configure Git
              run: |
                git config --global user.email "actions@github.com"
                git config --global user.name "GitHub Actions"

            - name: Commit changes
              run: |
                git add .
                git commit -m "Add daily entry for $(date + '%Y-%m-%d')$"
                git push